{
 "title": "Monitor",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Store Income over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(transaction.datetime,$__interval),\n  store.location,\n  sum(transaction.total_amount) as amount\nFROM transaction\nJOIN store ON store.id = transaction.store_id\nWHERE\n  $__unixEpochFilter(transaction.datetime)\nGROUP BY 1, 2\nORDER BY 3 desc"
    }
   ]
  },
  {
   "title": "Income per shop",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  store.location,\n  sum(transaction.total_amount) as amount\nFROM transaction\nJOIN store ON store.id = transaction.store_id\nWHERE\n  $__unixEpochFilter(transaction.datetime)\nGROUP BY store.location\nORDER BY amount desc"
    }
   ]
  },
  {
   "title": "Payment by type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(datetime,$__interval),\n  sum(total_amount) AS \"Cash\"\nFROM \"transaction\"\nWHERE\n  $__unixEpochFilter(datetime) AND\n  payment_type = 'CASH'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(datetime,$__interval),\n  sum(total_amount) AS \"Card\"\nFROM \"transaction\"\nWHERE\n  $__unixEpochFilter(datetime) AND\n  payment_type = 'CARD'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Income",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "yaxes": [
    { "format": "currencyGBP" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(datetime,$__interval),\n  sum(total_amount) AS \"total_amount\"\nFROM \"transaction\"\nWHERE\n  $__unixEpochFilter(datetime)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Top Grossing Products",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  -- $__unixEpochGroupAlias(transaction.datetime,$__interval),\n  sum(transaction.total_amount) as total,\n  case \n    when product_type.name = 'Unidentified' THEN product.name\n    else product_type.name + ' ' + product.name\n  END as name\nFROM transaction\nJOIN basket ON basket.transaction_id = transaction.id\nJOIN product ON product.id = basket.product_id\nJOIN product_type ON product_type.id = product.type_id\nWHERE\n  $__unixEpochFilter(transaction.datetime)\nGROUP BY 2\nORDER BY 1 DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Top Grossing Products per Store",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with best_selling as (\n  select \n    store.location as store_name,\n    case \n      when product_type.name = 'Unidentified'\n        THEN product.name\n      else product_type.name + ' ' + product.name\n    END as nname,\n    sum(product.price) as price_sum,\n    ROW_NUMBER() OVER (PARTITION by store.location order by sum(product.price) DESC) as rn\n    from transaction\n    join basket on basket.transaction_id = transaction.id\n    join product on product.id = basket.product_id\n    join product_type on product_type.id = product.type_id\n    JOIN store on store.id = transaction.store_id\n    where $__unixEpochFilter(transaction.datetime)\n    group by store.location, nname\n  )\n\n\nSELECT\n  best_selling.store_name,\n  best_selling.nname,\n  best_selling.price_sum\n  from best_selling\n  where rn < 4\n  order by best_selling.store_name, best_selling.price_sum DESC"
    }
   ]
  },
  {
   "title": "Pipeline Check",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "FunctionName": "lifehakk-group-project-v2-dev-execute"
     },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": {
      "FunctionName": "lifehakk-group-project-v2-dev-execute"
     },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": {
      "FunctionName": "lifehakk-group-project-v2-dev-execute"
     },
     "metricName": "ConcurrentExecutions",
     "namespace": "AWS/Lambda",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "S3 bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "BucketName": "lifehakk-v2", "StorageType": "AllStorageTypes" },
     "metricName": "NumberOfObjects",
     "namespace": "AWS/S3",
     "region": "eu-west-1",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}